version: 2.1

executors:
  python:
    docker:
    - image: circleci/python:3.8

jobs:
  build-and-test:
    executor: python
    steps:
      - checkout
      - run:
          name: Install Python deps
          command: pip3 install -r requirements.txt
      - run:
          command: python3 test.py
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
