version: 2.1

executors:
  python:
    docker:
    - image: circleci/python:3.7

jobs:
  build-and-test:
    executor: python
    steps:
      - checkout
      - run:
          command: ./test.py
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
