version: 2.1

jobs:
  build-and-test:
    executor: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: ./test.py
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
