version: 2.1

executors:
  python:
    docker:
    - image: ubuntu:20.04

jobs:
  build-and-test:
    executor: python
    steps:
      - checkout
      - run:
          name: upgrade pip
          command: /usr/local/bin/python -m pip install --upgrade pip
      - run:
          name: Install Python deps
          command: pip3 install -r requirements.txt
      - run:
          command: python3 test.py
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
